services:
  redis:
    image: redis:latest
    volumes:
      - orm_data_redis:/data
    ports:
      - "4000:6379"
  mysql:
    image: mysql:8.0
    ports:
      - "4001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file: ".env"
    volumes:
      - orm_data_mysql:/var/lib/mysql


volumes:
  orm_data_mysql:
  orm_data_redis:
